#!/bin/bash

# colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NOCLR='\033[0m'

# testing error detections

COUNT=4
TEST[1]=lexical_errors
TEST[2]=syntax_errors
TEST[3]=definition_errors
TEST[4]=type_errors
# syntax tests

for ((i=1; i <= COUNT ; i++));do

    echo "${TEST[$i]}:"|sed 's/_/ /g'|awk '{print toupper($0)}'
    DIR=testsuites/errors/${TEST[$i]}/*

    for sample in $DIR;do

        ./ifj $sample 2> /dev/null
        result="`echo $?`"
        if [ $result -eq $i ]; then
            printf "${GREEN}OK${NOCLR}\n"
        else
            printf "${RED}Wrong${NOCLR} - $sample\n"
        fi
    done
done

