#!/bin/bash

# colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NOCLR='\033[0m'

IFJ=testsuites/ifj16.java
DIR=testsuites/interpret/*.java

for i in $DIR; do
  ifile="`echo "$i"|sed 's/java/input/g'`"
  if [ ! -f "$ifile" ];then
    ifile="`echo "$i"|sed 's/ifj16.java/input/g'`"
  fi

  cat $IFJ $i > tmp.java
  javac tmp.java
  if [ -f "$ifile" ];then
    res="`./ifj $i < $ifile`"
    out="`java ifj16 < $ifile`"
  else
    res="`./ifj $i`"
    out="`java ifj16`"
  fi

  if [ "$res" == "$out" ];then
    printf "${GREEN}OK${NOCLR}\n"
  else
    printf "${RED}Wrong${NOCLR} - $i\n"
  fi
done

rm tmp.java *.class


# tests with *.out

DIR=testsuites/tests_output/*.java

for i in $DIR; do
  ifile="`echo "$i"|sed 's/java/input/g'`"

  if [ ! -f "$ifile" ];then
    ifile="`echo "$i"|sed 's/ifj16.java/input/g'`"
  fi

  if [ -f "$ifile" ];then
    res="`./ifj $i < $ifile`"
  else
    res="`./ifj $i`"
  fi
  ofile="`echo "$i"|sed 's/java/output/g'`"
  out="`cat $ofile`"
  if [ "$res" == "$out" ];then
    printf "${GREEN}OK${NOCLR}\n"
  else
    printf "${RED}Wrong${NOCLR} - $i\n"
    echo "$out"
    echo "======="
    echo "$res"
  fi

done


