#!/bin/bash

# colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NOCLR='\033[0m'

IFJ=testsuites/ifj16.java
DIR=testsuites/interpret/*.java

for i in $DIR; do

  # input file if any
  ifile="`echo "$i"|sed 's/java/input/g'`"
  if [ ! -f "$ifile" ];then
    ifile="`echo "$i"|sed 's/ifj16.java/input/g'`"
  fi

  # output file if any
  ofile="`echo "$i"|sed 's/java/output/g'`"
  if [ ! -f "$ifile" ];then
    ofile="`echo "$i"|sed 's/ifj16.java/output/g'`"
  fi

  if [ -f "$ifile" ];then
    res="`./ifj $i < $ifile`"
    if [ -f "$ofile" ];then
      out="`cat $ofile`"
    else
      cat $IFJ $i > tmp.java
      javac tmp.java
      out="`java ifj16 < $ifile`"
    fi
  else
    res="`./ifj $i`"
    if [ -f "$ofile" ];then
      out="`cat $ofile`"
    else
      cat $IFJ $i > tmp.java
      javac tmp.java
      out="`java ifj16`"
    fi
  fi

  if [ "$res" == "$out" ];then
    printf "${GREEN}OK${NOCLR}\n"
  else
    printf "${RED}Wrong${NOCLR} - $i\n"
  fi
done

rm tmp.java *.class

